name: orion-finance-sdk-py

plugins:
  - name: foundry
  - name: alchemy
  - name: etherscan

ethereum:
  mainnet_fork:
    default_provider: foundry
  sepolia_fork:
    default_provider: foundry

foundry:
  host: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
